import '../app/styles/globals.css'
import  "react-datepicker/dist/react-datepicker.css"
import { Providers } from "./providers";
import MainLayout from "./src/layouts";

export const metadata = {
  title: "Turborvip",
  description: "Generated by Turborvip",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <MainLayout>{children}</MainLayout>
          {/* <ToastContainer /> */}
        </Providers>
      </body>
    </html>
  );
}
