import { createStandaloneToast } from '@chakra-ui/react'
import { Providers } from "./providers";
import MainLayout from "./src/layouts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <MainLayout>{children}</MainLayout>
          {/* <ToastContainer /> */}
        </Providers>
      </body>
    </html>
  );
}
